package com.mooo.hairyone.td5tester;

import java.util.EnumMap;

public class TD5_Pids {

    enum Pid {
        INIT_FRAME, START_DIAGNOSTICS, REQUEST_SEED, KEY_RETURN,
        ENGINE_RPM, BATTERY_VOLTAGE, VEHICLE_SPEED, START_FUELLING,
        TEMPERATURES, MAP_MAF, AMBIENT_PRESSURE, THROTTLE_POSITION,
        POWER_BALANCE, RPM_ERROR, EGR_MODULE, INLET_MODULE,
        WASTEGATE_MODULE, KEEP_ALIVE, FAULT_CODES, CLEAR_FAULTS,
        GET_INPUTS, GET_FUEL_DEMAND
    }

    ;

}